name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      working-directory: ./WebApp1
      run: dotnet restore
    - name: Build
      working-directory: ./WebApp1
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./WebApp1
      run: dotnet test --no-build --verbosity normal
deploy:
  runs-on: ubuntu-latest
     needs: docker_build_and_push
    steps:
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
        
    - name: Azure CLI Start Staging Slot
      uses: Azure/cli@1.0.4
      with:
       inlineScript: az webapp start --name $webapp_name --resource-group $resource_group --slot staging
      
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.webapp_name }}
