name: .NET
env:
  url: https://app-github-demo.azurewebsites.net
  webapp_name: app-github-demo
  resource_group: GitHubDemo
  AZURE_WEBAPP_PACKAGE_PATH: '.'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      working-directory: ./WebApp1
      run: dotnet restore
    - name: Build
      working-directory: ./WebApp1
      run:  |
        dotnet build --no-restore
        dotnet publish -c Release -o output
    - name: Test
      working-directory: ./WebApp1
      run: dotnet test --no-build --verbosity normal
  
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.webapp_name }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: './output'
